learning_templates/basic_app/urls.py
from django.conf.urls import url 
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="nabar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">BRAND</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
                <li><a href="{% url 'basic_app:other' %}" class="navbar-link">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body-block %}
            <!-- Anything outside of this will be inherited if you enxtend! -->
        {% endblock %}
    </div>
    
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
   {% block body_block %} 
    <h1>WELCOME TO THE INDEX PAGE!</h1>
    <h2>This is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
   {% block body_block %} 
    <h1>WELCOME TO THE OTHER PAGE!</h1>
    <h2>This is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>

</body>
</html>